import 'package:training_log_app/devtools/demo_fixture_models.dart';

enum ScreenshotCaptureStep {
  homeDefault,
  homeKeepLoggingToday,
  homeSetCurrentSplit,
  homeRecoveryLastUsedExists,
  homeRecoveryLastUsedDeleted,
  homeRecentSessionsPopulated,
  homeRecentSessionsEmpty,
  splitsList,
  splitDetail,
  splitBuilder,
  exercisesList,
  exerciseHistory,
  exerciseLabelsEditor,
  labelsCatalog,
  loggerSplitDayInitial,
  loggerSplitDayWithInputs,
  loggerFreeEmpty,
  loggerFreeWithExercises,
  loggerExercisePickerOpen,
  loggerFinishUnfilledWarning,
  loggerDeleteCurrentLogConfirmDialog,
  sessionOverviewEditable,
  sessionOverviewDeleteConfirmDialog,
  splitBuilderExercisePickerOpen,
  exercisesDeleteModeActive,
  exercisesHideStandardConfirmDialog,
  exercisesRestoreStandardConfirmDialog,
}

class ScreenshotManifestEntry {
  const ScreenshotManifestEntry({
    required this.id,
    required this.title,
    required this.order,
    required this.scenario,
    required this.captureStep,
    required this.routeGroup,
    required this.notes,
  });

  final String id;
  final String title;
  final int order;
  final DemoFixtureScenario scenario;
  final ScreenshotCaptureStep captureStep;
  final String routeGroup;
  final String notes;
}

const screenshotManifest = <ScreenshotManifestEntry>[
  ScreenshotManifestEntry(
    id: 'home_next_workout',
    title: 'Home - next workout',
    order: 1,
    scenario: DemoFixtureScenario.baseRealistic,
    captureStep: ScreenshotCaptureStep.homeDefault,
    routeGroup: 'home',
    notes: 'Primary Home state with sequence suggestion card.',
  ),
  ScreenshotManifestEntry(
    id: 'home_keep_logging_today',
    title: 'Home - keep logging today',
    order: 2,
    scenario: DemoFixtureScenario.homeKeepLoggingToday,
    captureStep: ScreenshotCaptureStep.homeKeepLoggingToday,
    routeGroup: 'home',
    notes: 'In-progress draft session resume state.',
  ),
  ScreenshotManifestEntry(
    id: 'home_set_current_split',
    title: 'Home - set current split',
    order: 3,
    scenario: DemoFixtureScenario.homeNoCurrentSplit,
    captureStep: ScreenshotCaptureStep.homeSetCurrentSplit,
    routeGroup: 'home',
    notes: 'No active split assigned.',
  ),
  ScreenshotManifestEntry(
    id: 'home_recovery_last_used_exists',
    title: 'Home - recovery when last used split exists',
    order: 4,
    scenario: DemoFixtureScenario.homeLastUsedExistsNotCurrent,
    captureStep: ScreenshotCaptureStep.homeRecoveryLastUsedExists,
    routeGroup: 'home',
    notes: 'Last used split differs from active but still exists.',
  ),
  ScreenshotManifestEntry(
    id: 'home_recovery_last_used_deleted',
    title: 'Home - recovery when last used split deleted',
    order: 5,
    scenario: DemoFixtureScenario.homeLastUsedDeleted,
    captureStep: ScreenshotCaptureStep.homeRecoveryLastUsedDeleted,
    routeGroup: 'home',
    notes: 'Last used split reference no longer exists.',
  ),
  ScreenshotManifestEntry(
    id: 'home_recent_sessions_populated',
    title: 'Home - recent sessions populated',
    order: 6,
    scenario: DemoFixtureScenario.baseRealistic,
    captureStep: ScreenshotCaptureStep.homeRecentSessionsPopulated,
    routeGroup: 'home',
    notes: 'Recent sessions list is visible and populated.',
  ),
  ScreenshotManifestEntry(
    id: 'home_recent_sessions_empty',
    title: 'Home - recent sessions empty',
    order: 7,
    scenario: DemoFixtureScenario.homeNoSessions,
    captureStep: ScreenshotCaptureStep.homeRecentSessionsEmpty,
    routeGroup: 'home',
    notes: 'Recent sessions empty state.',
  ),
  ScreenshotManifestEntry(
    id: 'splits_list',
    title: 'Splits - list',
    order: 8,
    scenario: DemoFixtureScenario.baseRealistic,
    captureStep: ScreenshotCaptureStep.splitsList,
    routeGroup: 'splits',
    notes: 'Active split + all splits list.',
  ),
  ScreenshotManifestEntry(
    id: 'split_detail',
    title: 'Splits - detail',
    order: 9,
    scenario: DemoFixtureScenario.baseRealistic,
    captureStep: ScreenshotCaptureStep.splitDetail,
    routeGroup: 'splits',
    notes: 'Selected split detail page.',
  ),
  ScreenshotManifestEntry(
    id: 'split_builder',
    title: 'Splits - builder',
    order: 10,
    scenario: DemoFixtureScenario.baseRealistic,
    captureStep: ScreenshotCaptureStep.splitBuilder,
    routeGroup: 'splits',
    notes: 'Split builder creation screen.',
  ),
  ScreenshotManifestEntry(
    id: 'exercises_list',
    title: 'Exercises - list',
    order: 11,
    scenario: DemoFixtureScenario.baseRealistic,
    captureStep: ScreenshotCaptureStep.exercisesList,
    routeGroup: 'exercises',
    notes: 'Exercise catalog list.',
  ),
  ScreenshotManifestEntry(
    id: 'exercise_history',
    title: 'Exercises - history',
    order: 12,
    scenario: DemoFixtureScenario.baseRealistic,
    captureStep: ScreenshotCaptureStep.exerciseHistory,
    routeGroup: 'exercises',
    notes: 'Exercise performance history view.',
  ),
  ScreenshotManifestEntry(
    id: 'exercise_labels_editor',
    title: 'Exercises - labels editor',
    order: 13,
    scenario: DemoFixtureScenario.baseRealistic,
    captureStep: ScreenshotCaptureStep.exerciseLabelsEditor,
    routeGroup: 'exercises',
    notes: 'Edit labels screen for one exercise.',
  ),
  ScreenshotManifestEntry(
    id: 'labels_catalog',
    title: 'Other - labels catalog',
    order: 14,
    scenario: DemoFixtureScenario.baseRealistic,
    captureStep: ScreenshotCaptureStep.labelsCatalog,
    routeGroup: 'other',
    notes: 'Global labels browsing screen.',
  ),
  ScreenshotManifestEntry(
    id: 'logger_split_day_initial',
    title: 'Logger - split day initial',
    order: 15,
    scenario: DemoFixtureScenario.baseRealistic,
    captureStep: ScreenshotCaptureStep.loggerSplitDayInitial,
    routeGroup: 'logger',
    notes: 'Split-day logger before input.',
  ),
  ScreenshotManifestEntry(
    id: 'logger_split_day_with_inputs',
    title: 'Logger - split day with inputs',
    order: 16,
    scenario: DemoFixtureScenario.baseRealistic,
    captureStep: ScreenshotCaptureStep.loggerSplitDayWithInputs,
    routeGroup: 'logger',
    notes: 'Split-day logger with active set entry.',
  ),
  ScreenshotManifestEntry(
    id: 'logger_free_empty',
    title: 'Logger - free empty',
    order: 17,
    scenario: DemoFixtureScenario.baseRealistic,
    captureStep: ScreenshotCaptureStep.loggerFreeEmpty,
    routeGroup: 'logger',
    notes: 'Free workout mode initial state.',
  ),
  ScreenshotManifestEntry(
    id: 'logger_free_with_exercises',
    title: 'Logger - free with exercises',
    order: 18,
    scenario: DemoFixtureScenario.baseRealistic,
    captureStep: ScreenshotCaptureStep.loggerFreeWithExercises,
    routeGroup: 'logger',
    notes: 'Free workout after selecting an exercise.',
  ),
  ScreenshotManifestEntry(
    id: 'logger_exercise_picker_open',
    title: 'Logger - exercise picker',
    order: 19,
    scenario: DemoFixtureScenario.baseRealistic,
    captureStep: ScreenshotCaptureStep.loggerExercisePickerOpen,
    routeGroup: 'logger',
    notes: 'Free workout full-screen exercise picker.',
  ),
  ScreenshotManifestEntry(
    id: 'logger_finish_unfilled_warning',
    title: 'Logger - finish with unfilled warning',
    order: 20,
    scenario: DemoFixtureScenario.loggerSplitWithUnfilledRows,
    captureStep: ScreenshotCaptureStep.loggerFinishUnfilledWarning,
    routeGroup: 'logger',
    notes: 'Finish sheet warning for unfilled sets.',
  ),
  ScreenshotManifestEntry(
    id: 'logger_delete_current_log_confirm_dialog',
    title: 'Logger - delete current log confirm',
    order: 21,
    scenario: DemoFixtureScenario.baseRealistic,
    captureStep: ScreenshotCaptureStep.loggerDeleteCurrentLogConfirmDialog,
    routeGroup: 'logger',
    notes: 'Delete current log confirmation dialog.',
  ),
  ScreenshotManifestEntry(
    id: 'session_overview_editable',
    title: 'Session overview editable',
    order: 22,
    scenario: DemoFixtureScenario.baseRealistic,
    captureStep: ScreenshotCaptureStep.sessionOverviewEditable,
    routeGroup: 'sessions',
    notes: 'Session overview screen with editable fields.',
  ),
  ScreenshotManifestEntry(
    id: 'session_overview_delete_confirm_dialog',
    title: 'Session overview delete confirmation',
    order: 23,
    scenario: DemoFixtureScenario.baseRealistic,
    captureStep: ScreenshotCaptureStep.sessionOverviewDeleteConfirmDialog,
    routeGroup: 'sessions',
    notes: 'Delete session confirmation dialog.',
  ),
  ScreenshotManifestEntry(
    id: 'split_builder_exercise_picker_open',
    title: 'Split builder - exercise picker',
    order: 24,
    scenario: DemoFixtureScenario.baseRealistic,
    captureStep: ScreenshotCaptureStep.splitBuilderExercisePickerOpen,
    routeGroup: 'splits',
    notes: 'Full-screen exercise picker in split builder.',
  ),
  ScreenshotManifestEntry(
    id: 'exercises_delete_mode_active',
    title: 'Exercises - delete mode active',
    order: 25,
    scenario: DemoFixtureScenario.baseRealistic,
    captureStep: ScreenshotCaptureStep.exercisesDeleteModeActive,
    routeGroup: 'exercises',
    notes: 'Delete/hide mode visual state in exercises list.',
  ),
  ScreenshotManifestEntry(
    id: 'exercises_hide_standard_confirm_dialog',
    title: 'Exercises - hide standard confirmation',
    order: 26,
    scenario: DemoFixtureScenario.baseRealistic,
    captureStep: ScreenshotCaptureStep.exercisesHideStandardConfirmDialog,
    routeGroup: 'exercises',
    notes: 'Confirmation dialog before hiding standard exercise.',
  ),
  ScreenshotManifestEntry(
    id: 'exercises_restore_standard_confirm_dialog',
    title: 'Exercises - restore standard confirmation',
    order: 27,
    scenario: DemoFixtureScenario.baseRealistic,
    captureStep: ScreenshotCaptureStep.exercisesRestoreStandardConfirmDialog,
    routeGroup: 'exercises',
    notes: 'Confirmation dialog before restoring hidden standard exercise.',
  ),
];
